### ISSUE TITLE
InvalidChunkRangeException

### ISSUE THREAD

**Issue by VeniaminSychev** [TristanBilot/dfetch#6]
Hello,
Thank you for a such useful library!

I am trying to fetch the table as it mentioned on the column that contains distinct values, but anyway getting an error:

**InvalidChunkRangeException**: _Difference of range between elements of column datetime_tzutc                 is too high: more than 25.0% of elements are too far from the mean._

Could you, please, give me advices how should I handle this case?
Thank you in advance!

Best,
Veniamin

**Comment by TristanBilot** [comment]
Hi Veniamin,

Thanks for using bqfetch!
This error means that the column you chose for indexing: "datetime_tzutc", is not a good index column, namely there are chances that if you request 2GB of data during one fetch, you could end up with a fetch of 5GB resulting in memory overflow. I give some good examples of index column in the README. 

However, in the latest version of bqfetch that I just released, this exception is transformed in a warning message, so it could work, but keep in mind that the partitioning of your tables will not be good using this column!

To install latest version, please run `pip install --upgrade bqfetch`.

**Comment by VeniaminSychev** [comment]
Thank you, Tristan, for a quick response! 
I will upgrade the library and check README file once again.
